const locales = {
  id: {
    // voice State Update
    voice_join_title: '🔊 Join Voice',
    voice_join_desc: (user, channel) => `${user} bergabung ke ${channel}.`,
    voice_leave_title: '🔇 Leave Voice',
    voice_leave_desc: (user, channel) => `${user} keluar dari ${channel}.`,
    voice_move_title: '🔄 Pindah Voice',
    voice_move_desc: (user, oldChannel, newChannel) => `${user} pindah dari ${oldChannel} ke ${newChannel}.`,
    voice_before: 'Sebelum',
    voice_after: 'Sesudah',
    voice_duration_title: 'Durasi Sesi',
    voice_duration_val: (h, m, s) => `${h}j ${m}m ${s}d`,
    voice_mic_mute_title: '🎙️ Mic Mati',
    voice_mic_unmute_title: '🎙️ Mic Aktif',
    voice_mic_mute_desc: (user, channel) => `${user} mematikan mic di ${channel}.`,
    voice_mic_unmute_desc: (user, channel) => `${user} menyalakan mic di ${channel}.`,
    voice_deaf_mute_title: '🎧 Audio Mati',
    voice_deaf_unmute_title: '🎧 Audio Aktif',
    voice_deaf_mute_desc: (user, channel) => `${user} mematikan audio di ${channel}.`,
    voice_deaf_unmute_desc: (user, channel) => `${user} menyalakan audio di ${channel}.`,
    voice_cam_on_title: '📷 Kamera Aktif',
    voice_cam_off_title: '📷 Kamera Mati',
    voice_cam_on_desc: (user, channel) => `${user} menyalakan kamera di ${channel}.`,
    voice_cam_off_desc: (user, channel) => `${user} mematikan kamera di ${channel}.`,
    voice_stream_on_title: '🖥️ Share Screen',
    voice_stream_off_title: '🖥️ Share Screen Berhenti',
    voice_stream_on_desc: (user, channel) => `${user} berbagi layar di ${channel}.`,
    voice_stream_off_desc: (user, channel) => `${user} berhenti berbagi layar di ${channel}.`,
    voice_status_update_title: '💬 Status Voice',
    voice_status_update_desc: (user, channel) => `${user} ubah status voice di ${channel}.`,

    // presence Update
    pres_status_title: '👤 Status Berubah',
    pres_status_desc: (user) => `Status ${user} berubah.`,
    pres_status_old: 'Lama',
    pres_status_new: 'Baru',
    pres_game_stop_title: '🎮 Selesai Main',
    pres_game_stop_desc: (user, game, mins) => `${user} selesai main **${game}** (${mins}m).`,
    pres_game_start_title: '🎮 Mulai Main',
    pres_game_start_desc: (user, game) => `${user} mulai main **${game}**.`,
    pres_game_detail: 'Detail Aktivitas',
    pres_spotify_title: '🎵 Spotify',
    pres_spotify_desc: (user) => `${user} mendengarkan Spotify.`,
    pres_spotify_song: 'Lagu',
    pres_spotify_artist: 'Artis',

    // message Create (Moderation warnings)
    msg_mod_invite_title: '⚠️ Link Invite',
    msg_mod_invite_desc: (user, channel) => `${user} kirim link invite di ${channel}.`,
    msg_mod_mention_title: '⚠️ Mass Mention',
    msg_mod_mention_desc: (user, channel) => `${user} melakukan mass mention di ${channel}.`,
    msg_mod_toxic_title: '⚠️ Kata Kasar',
    msg_mod_toxic_desc: (user, channel) => `${user} berkata kasar di ${channel}.`,
    msg_mod_field_content: 'Konten',
    msg_mod_field_count: 'Jumlah Penyebutan',

    // message Delete
    msg_del_title: '🗑️ Pesan Dihapus',
    msg_del_desc: 'Pesan dihapus.',
    msg_del_sender: 'Pengirim',
    msg_del_channel: 'Saluran',
    msg_del_content: 'Konten',
    msg_del_attachments: 'Lampiran',
    msg_del_by: 'Dihapus Oleh',

    // message Delete Bulk
    msg_bulk_title: '🗑️ Hapus Massal',
    msg_bulk_desc: (count, channel) => `**${count}** pesan dihapus di ${channel}.`,
    msg_bulk_by: 'Dihapus Oleh',

    // message Update
    msg_update_title: '📝 Pesan Diedit',
    msg_update_desc: 'Pesan disunting.',
    msg_update_sender: 'Pengirim',
    msg_update_channel: 'Saluran',
    msg_update_before: 'Sebelum',
    msg_update_after: 'Sesudah',

    // guild Member Add
    mem_add_title: '📥 Member Join',
    mem_add_desc: (user) => `${user} bergabung ke server.`,
    mem_add_age: 'Umur Akun',
    mem_add_age_val: (days) => `${days} hari`,
    mem_add_total: 'Total Member',
    mem_add_total_val: (count) => `${count} anggota`,

    // guild Member Remove
    mem_rem_title: '📤 Member Leave',
    mem_rem_desc: (user) => `${user} meninggalkan server.`,
    mem_rem_joined: 'Bergabung',
    mem_rem_total: 'Total Member',
    mem_rem_total_val: (count) => `${count} anggota`,

    // guild Member Update
    mem_update_nick_title: '👤 Nickname Berubah',
    mem_update_nick_desc: (user) => `Nickname ${user} diubah.`,
    mem_update_role_add_title: '🛡️ Role Ditambah',
    mem_update_role_add_desc: (user) => `${user} mendapat role.`,
    mem_update_role_rem_title: '🛡️ Role Dihapus',
    mem_update_role_rem_desc: (user) => `${user} kehilangan role.`,
    mem_update_role_field: 'Role',
    mem_update_by_field: 'Oleh',

    // guild Audit Log Entry Create
    audit_ban_title: '🚫 Ban',
    audit_ban_desc: (target) => `**${target}** diblokir.`,
    audit_unban_title: '🔓 Unban',
    audit_unban_desc: (target) => `Ban **${target}** dicabut.`,
    audit_kick_title: '👢 Kick',
    audit_kick_desc: (target) => `**${target}** dikick.`,
    audit_timeout_title: '⏳ Timeout',
    audit_timeout_desc: (target) => `**${target}** ditimeout.`,
    audit_untimeout_title: '⏰ Timeout Selesai',
    audit_untimeout_desc: (target) => `Timeout **${target}** dicabut.`,
    audit_chan_create_title: '📁 Channel Dibuat',
    audit_chan_create_desc: 'Channel dibuat.',
    audit_chan_delete_title: '📂 Channel Dihapus',
    audit_chan_delete_desc: (name) => `Channel **#${name}** dihapus.`,
    audit_chan_update_title: '📂 Channel Diupdate',
    audit_chan_update_desc: (channel) => `Channel ${channel} diupdate.`,
    audit_role_create_title: '🛡️ Role Dibuat',
    audit_role_create_desc: 'Role dibuat.',
    audit_role_delete_title: '🛡️ Role Dihapus',
    audit_role_delete_desc: (name) => `Role **@${name}** dihapus.`,
    audit_role_update_title: '🛡️ Role Diupdate',
    audit_role_update_desc: (role) => `Role ${role} diupdate.`,
    audit_emoji_create_title: '😀 Emoji Dibuat',
    audit_emoji_create_desc: (name) => `Emoji \`:${name}:\` ditambahkan.`,
    audit_emoji_delete_title: '😢 Emoji Dihapus',
    audit_emoji_delete_desc: (name) => `Emoji \`:${name}:\` dihapus.`,
    audit_vc_status_update_title: '🎙️ Status VC Diupdate',
    audit_vc_status_update_desc: (channel) => `Status VC ${channel} diubah.`,
    audit_vc_status_delete_title: '🎙️ Status VC Dihapus',
    audit_vc_status_delete_desc: (channel) => `Status VC ${channel} dihapus.`,
    audit_field_target: 'Target',
    audit_field_mod: 'Moderator',
    audit_field_reason: 'Alasan',
    audit_field_duration: 'Durasi',
    audit_field_duration_val: (mins) => `${mins} menit`,
    audit_field_chan: 'Channel',
    audit_field_role: 'Role',
    audit_field_emoji: 'Emoji',
    audit_field_by: 'Oleh'
  },
  en: {
    // voice State Update
    voice_join_title: '🔊 Voice Joined',
    voice_join_desc: (user, channel) => `${user} joined ${channel}.`,
    voice_leave_title: '🔇 Voice Left',
    voice_leave_desc: (user, channel) => `${user} left ${channel}.`,
    voice_move_title: '🔄 Voice Moved',
    voice_move_desc: (user, oldChannel, newChannel) => `${user} moved from ${oldChannel} to ${newChannel}.`,
    voice_before: 'Before',
    voice_after: 'After',
    voice_duration_title: 'Duration',
    voice_duration_val: (h, m, s) => `${h}h ${m}m ${s}s`,
    voice_mic_mute_title: '🎙️ Mic Muted',
    voice_mic_unmute_title: '🎙️ Mic Active',
    voice_mic_mute_desc: (user, channel) => `${user} muted mic in ${channel}.`,
    voice_mic_unmute_desc: (user, channel) => `${user} unmuted mic in ${channel}.`,
    voice_deaf_mute_title: '🎧 Audio Muted',
    voice_deaf_unmute_title: '🎧 Audio Active',
    voice_deaf_mute_desc: (user, channel) => `${user} deafened audio in ${channel}.`,
    voice_deaf_unmute_desc: (user, channel) => `${user} undeafened audio in ${channel}.`,
    voice_cam_on_title: '📷 Camera On',
    voice_cam_off_title: '📷 Camera Off',
    voice_cam_on_desc: (user, channel) => `${user} turned on camera in ${channel}.`,
    voice_cam_off_desc: (user, channel) => `${user} turned off camera in ${channel}.`,
    voice_stream_on_title: '🖥️ Screen Share',
    voice_stream_off_title: '🖥️ Screen Share Ended',
    voice_stream_on_desc: (user, channel) => `${user} started screen share in ${channel}.`,
    voice_stream_off_desc: (user, channel) => `${user} stopped screen share in ${channel}.`,
    voice_status_update_title: '💬 Voice Status',
    voice_status_update_desc: (user, channel) => `${user} updated voice status in ${channel}.`,

    // presence Update
    pres_status_title: '👤 Status Changed',
    pres_status_desc: (user) => `Status of ${user} changed.`,
    pres_status_old: 'Old',
    pres_status_new: 'New',
    pres_game_stop_title: '🎮 Stopped Playing',
    pres_game_stop_desc: (user, game, mins) => `${user} stopped playing **${game}** (${mins}m).`,
    pres_game_start_title: '🎮 Started Playing',
    pres_game_start_desc: (user, game) => `${user} started playing **${game}**.`,
    pres_game_detail: 'Activity Detail',
    pres_spotify_title: '🎵 Spotify',
    pres_spotify_desc: (user) => `${user} is listening to Spotify.`,
    pres_spotify_song: 'Song',
    pres_spotify_artist: 'Artist',

    // message Create (Moderation warnings)
    msg_mod_invite_title: '⚠️ Invite Link',
    msg_mod_invite_desc: (user, channel) => `${user} sent invite link in ${channel}.`,
    msg_mod_mention_title: '⚠️ Mass Mention',
    msg_mod_mention_desc: (user, channel) => `${user} did mass mention in ${channel}.`,
    msg_mod_toxic_title: '⚠️ Toxic Language',
    msg_mod_toxic_desc: (user, channel) => `${user} used bad words in ${channel}.`,
    msg_mod_field_content: 'Content',
    msg_mod_field_count: 'Mentions',

    // message Delete
    msg_del_title: '🗑️ Message Deleted',
    msg_del_desc: 'Message deleted.',
    msg_del_sender: 'Sender',
    msg_del_channel: 'Channel',
    msg_del_content: 'Content',
    msg_del_attachments: 'Attachments',
    msg_del_by: 'Deleted By',

    // message Delete Bulk
    msg_bulk_title: '🗑️ Bulk Deleted',
    msg_bulk_desc: (count, channel) => `**${count}** messages deleted in ${channel}.`,
    msg_bulk_by: 'Deleted By',

    // message Update
    msg_update_title: '📝 Message Edited',
    msg_update_desc: 'Message edited.',
    msg_update_sender: 'Sender',
    msg_update_channel: 'Channel',
    msg_update_before: 'Before',
    msg_update_after: 'After',

    // guild Member Add
    mem_add_title: '📥 Member Joined',
    mem_add_desc: (user) => `${user} joined the server.`,
    mem_add_age: 'Account Age',
    mem_add_age_val: (days) => `${days} days`,
    mem_add_total: 'Total Members',
    mem_add_total_val: (count) => `${count} members`,

    // guild Member Remove
    mem_rem_title: '📤 Member Left',
    mem_rem_desc: (user) => `${user} left the server.`,
    mem_rem_joined: 'Joined',
    mem_rem_total: 'Total Members',
    mem_rem_total_val: (count) => `${count} members`,

    // guild Member Update
    mem_update_nick_title: '👤 Nickname Changed',
    mem_update_nick_desc: (user) => `Nickname of ${user} changed.`,
    mem_update_role_add_title: '🛡️ Role Added',
    mem_update_role_add_desc: (user) => `${user} got a role.`,
    mem_update_role_rem_title: '🛡️ Role Removed',
    mem_update_role_rem_desc: (user) => `${user} lost a role.`,
    mem_update_role_field: 'Role',
    mem_update_by_field: 'By',

    // guild Audit Log Entry Create
    audit_ban_title: '🚫 Member Banned',
    audit_ban_desc: (target) => `**${target}** banned.`,
    audit_unban_title: '🔓 Member Unbanned',
    audit_unban_desc: (target) => `Ban of **${target}** removed.`,
    audit_kick_title: '👢 Member Kicked',
    audit_kick_desc: (target) => `**${target}** kicked.`,
    audit_timeout_title: '⏳ Member Muted',
    audit_timeout_desc: (target) => `**${target}** timed out.`,
    audit_untimeout_title: '⏰ Timeout Removed',
    audit_untimeout_desc: (target) => `Timeout of **${target}** removed.`,
    audit_chan_create_title: '📁 Channel Created',
    audit_chan_create_desc: 'Channel created.',
    audit_chan_delete_title: '📂 Channel Deleted',
    audit_chan_delete_desc: (name) => `Channel **#${name}** deleted.`,
    audit_chan_update_title: '📂 Channel Updated',
    audit_chan_update_desc: (channel) => `Channel ${channel} updated.`,
    audit_role_create_title: '🛡️ Role Created',
    audit_role_create_desc: 'Role created.',
    audit_role_delete_title: '🛡️ Role Deleted',
    audit_role_delete_desc: (name) => `Role **@${name}** deleted.`,
    audit_role_update_title: '🛡️ Role Updated',
    audit_role_update_desc: (role) => `Role ${role} updated.`,
    audit_emoji_create_title: '😀 Emoji Created',
    audit_emoji_create_desc: (name) => `Emoji \`:${name}:\` added.`,
    audit_emoji_delete_title: '😢 Emoji Deleted',
    audit_emoji_delete_desc: (name) => `Emoji \`:${name}:\` deleted.`,
    audit_vc_status_update_title: '🎙️ VC Status Updated',
    audit_vc_status_update_desc: (channel) => `VC status of ${channel} updated.`,
    audit_vc_status_delete_title: '🎙️ VC Status Deleted',
    audit_vc_status_delete_desc: (channel) => `VC status of ${channel} deleted.`,
    audit_field_target: 'Target',
    audit_field_mod: 'Moderator',
    audit_field_reason: 'Reason',
    audit_field_duration: 'Duration',
    audit_field_duration_val: (mins) => `${mins} minutes`,
    audit_field_chan: 'Channel',
    audit_field_role: 'Role',
    audit_field_emoji: 'Emoji',
    audit_field_by: 'By'
  }
};

function t(lang, key, ...args) {
  const dict = locales[lang] || locales['id'];
  const value = dict[key];
  if (typeof value === 'function') {
    return value(...args);
  }
  return value || key;
}

module.exports = { t };
